presensi/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.schemas import get_schema_view
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls'), name='tasks'),
    path('openapi', get_schema_view(
        title="Sistem Absensi",
        description="API untuk melakukan share data absensi dan kinerja",
        url="http://localhost:8000",
        version="1.0.0"
    ), name='openapi-schema'),
    path('swagger-ui/', TemplateView.as_view(
        template_name="swagger-ui.html",
        # extra_content={'schema_url':'openapi-schema'},
    ), name='swagger-ui')
    
]

task/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('save_peg/', views.save_pegawai, name='save_peg'),
    path('tugas/', views.tugas, name='tugas'),
    path('update_task/<int:pk>/', views.update_task, name='update_task'),
    path('api/tugas_harian/', views.Tugasharian_list.as_view(), name="tugas_harian"),
    path('api/tugas_harian/<int:pk>', views.Tugasharian_Detail.as_view(), name="tugas_detail"),
    path('api/absensi/', views.Absensi_list.as_view(), name="absensi"),
    path('api/absensi/<int:pk>/', views.Absensi_Detail.as_view(), name="absensi_detail"),
    path('hukuman/', views.hukuman_list, name='hukuman'),
    path('hukuman/buat/', views.buat_hukuman, name="buat-hukuman"),
]

task/models.py
from django.db import models
import datetime
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class MyAccountManager(BaseUserManager):
    def create_user(self, nama, username, password=None):
        if not username:
            raise ValueError("Users must have an username!")

        user = self.model(
            nama=nama,
            username = username
        )

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, nama, username, password=None):
        user = self.create_user(
            nama=nama,
            password=password,
            username = username,
        )
        user.is_admin = True
        user.is_staff = True
        user.save(using=self._db)

        return user


class Ms_Pegawai(models.Model):
    nip             = models.CharField(max_length=30)
    nip_pimpinan    = models.ForeignKey("self", on_delete=models.CASCADE, blank=True, null=True)
    nama            = models.CharField(max_length=75)
    pangkat         = models.CharField(max_length=7)
    nm_jabatan      = models.CharField(max_length=50)
    unit_kerja      = models.CharField(max_length=50)
    unor            = models.CharField(max_length=50)
    date_joined     = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login      = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin        = models.BooleanField(default=False)
    is_active       = models.BooleanField(default=True)
    is_staff        = models.BooleanField(default=False)
    is_superuser    = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['nama',]

    objects = MyAccountManager

    def __str__(self):
        return self.nama

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    # def __str__(self):
    #     return self.nama 

class Absensi(models.Model):
    nip             = models.ForeignKey(Ms_Pegawai, on_delete=models.CASCADE)
    tgl             = models.DateField()
    ket             = models.CharField(max_length=200, null=True)
    jam_masuk       = models.DateTimeField(null=True)
    jam_keluar      = models.DateTimeField(null=True)
    selisih         = models.FloatField(null=True, blank=True)
    latitude        = models.FloatField(null=True)
    longitude       = models.FloatField(null=True)
    nm_lokasi       = models.CharField(max_length=75)

    def __str__(self):
        return str(self.nip)   


class Ms_tugas_harian(models.Model):
    id_absensi      = models.ForeignKey(Absensi, on_delete=models.CASCADE)
    nm_tugas_harian = models.CharField(max_length=100)
    is_approved     = models.BooleanField(default=False)
    ket_tugas       = models.CharField(max_length=100, blank=True, null=True)
    status          = models.CharField(max_length=100, blank=True, null=True)
    nip_pimpinan    = models.ForeignKey(Ms_Pegawai, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nm_tugas_harian
   


class ijin_pindah_lokasi(models.Model):
    id_absensi      = models.ForeignKey(Absensi, on_delete=models.CASCADE)
    alasan          = models.CharField(max_length=70)
    lat_awal        = models.FloatField(null=True)
    long_awal       = models.FloatField(null=True)
    lokasi_awal     = models.CharField(max_length=75)
    lat_baru        = models.FloatField(null=True)
    long_baru       = models.FloatField(null=True)
    lokasi_baru     = models.CharField(max_length=75)

    def __str__(self):
        return self.alasan

class Hukuman(models.Model):
    ringan = "rn"
    sedang = "sd"
    berat = "br"
    pilihan_hukuman = [
        (ringan, 'Ringan'),
        (sedang, 'Sedang'),
        (berat, 'Berat'),
    ]
    
    nip = models.ForeignKey(Ms_Pegawai, on_delete=models.CASCADE)
    nip_pimpinan = models.ForeignKey(Ms_Pegawai, related_name="pimpinan", on_delete=models.CASCADE)
    jns_hukuman = models.CharField(max_length=50, choices=pilihan_hukuman, default=ringan,)
    teguran = models.CharField(max_length=100)

    def __str__(self):
        return self.teguran
    
# Create your models here.

task/forms.py
from django.forms import ModelForm
from .models import Ms_tugas_harian, Absensi, Hukuman


class TugasharianForm(ModelForm):
    class Meta:
        model = Ms_tugas_harian
        fields = ['id', 'id_absensi', 'nm_tugas_harian', 'is_approved', 'ket_tugas', 'status', 'nip_pimpinan']

class AbsensiForm(ModelForm):
    class Meta:
        model = Absensi
        fields = '__all__'

class HukumanForm(ModelForm):
    class Meta:
        model = Hukuman
        fields = ('nip', 'nip_pimpinan', 'jns_hukuman', 'teguran')

task/views.py
from django.shortcuts import render, HttpResponse, redirect
from rest_framework.parsers import JSONParser
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import generics, mixins
from rest_framework.schemas.openapi import SchemaGenerator
from rest_framework.decorators import api_view
from rest_framework import status
from rest_framework.schemas.openapi import AutoSchema

import coreapi
import coreschema

from .models import Ms_Pegawai, Absensi, ijin_pindah_lokasi, Ms_tugas_harian, Hukuman
# from django.utils.six import BytesIO
from .serializers import PegawaiSerializer
import requests
from django.core import serializers
from django.http import JsonResponse
from django.template.loader import render_to_string
import io
import json
from . import apitest
from .forms import TugasharianForm, AbsensiForm, HukumanForm
from django.contrib import messages
from .serializers import PegawaiSerializer, TugasHarianSerializer, AbsensiSerializer

import datetime



def home(request):
    #34.199.13.26/api/pegawai
    is_caches = ('data_peg' in request.session)
    if request.method=='POST':
        # data = request.POST.get('is_approve', False)
        post_pegawai = request.POST.getlist('nm_peg')
        id_absensi = request.POST.getlist('id_absensi')
        tugas_harian = Ms_tugas_harian.objects.all()
        pimpinan = Ms_Pegawai.objects.get(nama__startswith='Muhammad')
        is_approve = request.POST.getlist('is_approve')
        id_tugas_harian = request.POST.getlist('id')
        # presensi = Absensi.objects.
        selisih = len(id_tugas_harian) - len(is_approve)

        # for id in range(len(id_tugas_harian)):
        #     if len(is_approve)!=len(id_tugas_harian):
        #         if(is_approve[id]=='on'):
        #             is_approve[id]==True
        #         elif(is_approve[id]==''):
        #             is_approve[id]==False
        print("ini id tugas")
        print(request.POST.get('id_tugas'))


        # if len(is_approve)==0 and id_tugas_harian != 0:
        #     for i in id_tugas_harian:
        #         is_approve.append('False')
        # print(is_approve)
        count=0
        # print(id_tugas_harian)
        print(request.POST)
        for person, id in zip(post_pegawai, id_absensi):
            try:
                pegawai = Absensi.objects.get(id=int(id), nip__nama__startswith=person)
            except pegawai.DoesNotExist:
                continue
            
            # kehadiran = Absensi.objects.get()
            # print(person)
            # print(type(int(id)), id)
            # print(type(pegawai.id), id)
            # print(is_approve)
            
            for id_tgs, apr in zip(id_tugas_harian, is_approve):
                print(id_tgs)
                try:
                    new_tugas = Ms_tugas_harian.objects.get(id=int(id_tgs), id_absensi=pegawai.id)
                except new_tugas.DoesNotExist:
                    continue
                if apr=='on':
                    apr=True
                else:
                    apr=False
                print(id_tgs, apr)
                # new_tugas = Ms_tugas_harian(id=1,
                #                         id_absensi=Absensi.objects.get(id=1),
                #                         is_approved=is_approve1,
                #                         ket_tugas=request.POST.get('tambah_tugas1'),
                #                         # status=request.POST.get()
                #                         nip_pimpinan='1995012314')
            
            # tugas1 = request.POST.get('tambah_tugas{}'.format(person), False)
            # approved = request.POST.get('id_absensi.id', False)
            # tugas2 = request.POST.get('tambah_tugas2', False)
            # print(tugas1, approved)
        # print(  tugas_id)
        # new_tugas.save(update_fields=['id_absensi', 'is_approved', 'ket_tugas', 'nip_pimpinan'])
            count+=1
    #cache API agar lebih cepat saat load data
    # if not is_caches:
    #     ip_address = request.META.get('HTTP_X_FORWARDED_FOR', '')
    #     response = requests.get('http://localhost:8080/api/pegawai/')
    #     request.session['data_peg'] = response.json()
    
    # data_peg = request.session['data_peg']
    list_pegawai = []
    # for pegawai in data_peg:
    #     if pegawai['nip_pimpinan'] not None:
    #         if pegawai['nip_pimpinan']['id'] == 2:
    #             list_pegawai = pegawai['nip_pimpinan']
    pegawai = Ms_Pegawai.objects.all()
    kelima = 432000
    list_org_bermasalah = []
    for orang in pegawai:
        telat = Absensi.objects.filter(
           nip__nama = orang.nama,
           tgl__year = 2020, 
        ).values_list('selisih', flat=True)
        
        jml_telat=sum(telat)
        # jml_telat = datetime.timedelta(seconds=jml_telat)
        # jml_telat = jml_telat - datetime.timedelta(microseconds=jml_telat.microseconds)
        print(jml_telat)
        if jml_telat > kelima:
            list_org_bermasalah.append(orang)
    messages.warning(request, "Ada pegawai yang melanggar aturan!")
    print(list_org_bermasalah)

    pimpinan = Ms_Pegawai.objects.get(nip='199510102010121001')
    presensi = Absensi.objects.all()
    tugas_harian = Ms_tugas_harian.objects.all()
    pegawai = Ms_Pegawai.objects.filter(nip_pimpinan__nip='199510102010121001')
    print(list_pegawai)

    return render(request, 'core/home.html', {
        'data_peg': pegawai,
        'presensi': presensi,
        'tugas_harian': tugas_harian,
        'pimpinan': pimpinan,
        'is_caches': is_caches,
        
    })

def save_pegawai(request):
    pegawai = Ms_Pegawai.objects.all()
    id = apitest.id_list
    nip = apitest.nip_list
    nama = apitest.nama_list
    nip_pimpinan = apitest.nip_pimpinan_list
    unit_kerja = apitest.unit_kerja_list
    unor = apitest.unor_list
    pangkat = apitest.pangkat_list
    nm_jabatan = apitest.nm_jabatan_list
    
    hitung_pegawai = Ms_Pegawai.objects.all().count()
    print(len(id), hitung_pegawai)
    count_save = 0

    for i in range(len(id)):
        pegawai_exist = Ms_Pegawai.objects.filter(nip=nip[i]).count()
        if pegawai_exist == 0:
            value = Ms_Pegawai(
                                id = id[i],
                                nip = nip[i],
                                nama = nama[i],
                                unit_kerja = unit_kerja[i],
                                pangkat = pangkat[i],
                                unor = unor[i],
                                nm_jabatan=nm_jabatan[i],
                                # nip_pimpinan = Ms_Pegawai.objects.get(nip=nip_pimpinan[i])
                            )
            value.save()
            msg = '{} Data berhasil disimpan'.format(i+1)
        else:
            msg = 'Tidak ada data baru.'
    
    
    return render(request, 'core/savepeg.html', {'msg': msg})


def tugas(request):
    pegawai = Ms_Pegawai.objects.all()
    kelima = 432000
    list_org_bermasalah = []
    for orang in pegawai:
        telat = Absensi.objects.filter(
           nip__nama = orang.nama,
           tgl__year = 2020, 
        ).values_list('selisih', flat=True)
        
        jml_telat=sum(telat)
        # jml_telat = datetime.timedelta(seconds=jml_telat)
        # jml_telat = jml_telat - datetime.timedelta(microseconds=jml_telat.microseconds)
        print(jml_telat)
        if jml_telat > kelima:
            list_org_bermasalah.append(orang)
    messages.warning(request, "Ada pegawai yang melanggar aturan!")
    print(list_org_bermasalah)
    context = {
       
    }
    return render(request, 'core/tugas.html', context)

def update_task(request, pk):
    if request.method=='POST':
        tgs_harian = Ms_tugas_harian.objects.get(id=pk)
        is_approve = False
        
        print(tgs_harian.id)
        print(request.POST.get('is_approve'))
        if request.POST.get('is_approve') == "true":
            is_approve = True
        else:
            is_approve = False

        new_tugas = Ms_tugas_harian(id=pk,
                                     ket_tugas=request.POST.get('tambah_tugas'),
                                     is_approved=is_approve)
        new_tugas.save(update_fields=['ket_tugas', 'is_approved'])
        messages.success(request, "data disimpan")
    # return redirect(request, )
    
    #penambahan instance untuk dapat melakukan pengisian otomatis pada html
    tgs_harian = Ms_tugas_harian.objects.get(id=pk)
    tugasform = TugasharianForm(instance=tgs_harian)
    return render(request, 'core/update_task.html', {'tugasform':tugasform})
# Create your views here.
## return redirect('/') ini akan mengembalikan nilai ke halaman yang sama


class Tugasharian_list(generics.ListCreateAPIView):
    queryset = Ms_tugas_harian.objects.all()
    serializer_class = TugasHarianSerializer
    schema = AutoSchema(
        tags=['API Tugas Harian'],
        component_name='tgs_harian',
        operation_id_base='tgs_harian',
    )
    
class Tugasharian_Detail(generics.RetrieveUpdateAPIView):
    queryset = Ms_tugas_harian.objects.all()
    serializer_class = TugasHarianSerializer
    schema = AutoSchema(
        tags=['API Tugas Harian Detail'],
        component_name='tgs_harian_dtl',
        operation_id_base='tgs_harian_dtl',
    )
    
# @api_view(['GET', 'POST'])
# def tugasharian_list(request):
#     if request.method == 'GET':
#         tgs_harian = Ms_tugas_harian.objects.all()
#         tgs_serializer = TugasHarianSerializer(tgs_harian, many=True)
#         return Response(tgs_serializer.data)

#     elif request.method == 'POST':
#         tgs_serializer = TugasHarianSerializer(data=request.data)
#         if tgs_serializer.is_valid():
#             tgs_serializer.save()
#             return Response(tgs_serializer.data, status=status.HTTP_201_CREATED)
#         return Response(tgs_serializer.errors, status=status.HTTP_400_BAD_REQUEST)

task/templates/core/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <title>Sistem Absensi Pusjatan</title> 
    <nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
      <a class="navbar-brand" href="#"> Sistem Absensi Pusjatan</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    {% comment %} {%  if request.user.is_authenticated %} {% endcomment %}
       <ul class="navbar-nav mr-auto">
          <li {% if "/" == request.path %} class="nav-item active" {% endif %}>
            <a class="nav-link" href="{% url 'home' %}"> Home <span class="sr-only">(current)</span></a>
          </li>
          <li {% if "/hukuman/" == request.path %} class="nav-item active" {% endif %}>
            <a class="nav-link" href="{% url 'hukuman' %}"> Hukuman <span class="sr-only">(current)</span></a></li>
          
          {% comment %} </li>
          <li {% if "/about/" == request.path %} class="nav-item active" {% endif %}>
            <a class="nav-link" href="{% url 'about' %}"> Rekap Absen </a>
          </li>
          <li {% if "/rekap_tukin" == request.path %} class="nav-item active" {% endif %}>
            <a class="nav-link" href="{% url 'rekap_tukin' %}"> Rekap Tunjangan </a>
          </li> {% endcomment %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% comment %} <li class="nav-item"> <h5 class="my-2 float right text-light"> Hello, {{request.user.username}} </h5> </li> {% endcomment %}
            <button type="button" class="btn btn-primary" id="btn-notif">
              Notifications <span class="badge badge-light">4</span>
            </button>
        </ul>
        {% comment %} <!--    <a href="{% url 'login' %}"> Login </a> --> {% endcomment %}
        {% comment %} <ul class="nav navbar-nav navbar-right">
            <li class="nav-item"> <h5 class="my-2 float right text-light"> Hello, {{request.user.username}} </h5> </li>
            <li>  <a class="nav-link" href="{% url 'logout' %}">LogOut</a></li> 
        </ul> {% endcomment %}
   {% comment %}
    {% else %}

        <ul class="nav navbar-nav ml-auto">
            <li class="nav-item "><a class="nav-link" href="{% url 'login' %}">Login</a></li> 
        </ul>
    {% endif %} {% endcomment %}
      
     </div>
    </nav>
  </head>
  <body>
   
    <br/><br/></body>
    <div class="container">
    {% if messages %}
      {% for message in messages %}

        <div class="alert alert-warning alert-dismissible fade show" id="msg" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>


        
      {% endfor %}
    {% endif %}
    <br/><br/>
    
      {% block content %}
      {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="http://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{% static 'js/notif.js' %}"></script>
    {% block javascript %}
    
    {% endblock  %}
    <script>
      setTimeout(function(){
        if($('#msg').length > 0){
            $('#msg').remove();
        }
      }, 2000);
    </script>
  </body>
</html>

task/templates/core/home.html
{%extends 'core\base.html'%}

{% load static %}

{% block content %}

    <h1>Monitor tugas Pegawai</h1>
    
   
    <form action="/" method='POST'>
        {% csrf_token %}
        <h3>Pimpinan :  <input type="hidden" name="nm_pimpinan" value={{pimpinan.nama}}>{{pimpinan.nama}}</h3>
        <p></p>
        <div class="input-group mb-3">
                <label for="tgl_absensiid" class="col-sm-2">Tanggal</label>
                <input type="date" class="form-control col-sm-2" name="tgl_absensi" id="tgl_absensiid"> 
                <button class="btn btn-info" name="btn_cek_tgl"> cek tanggal</button>
        </div>
        {% for person in data_peg %} 
        <p></p>    
        <div class="tugas_pegawai">
            <p>Nama Pegawai : <input type="hidden" name="nm_peg" value={{person.nama}}><strong>{{person.nama}}</strong></p>
                
                <table class="table" id="table_absensi">
                        <thead class="table-primary">
                            <tr>
                                <td hidden>No</td>
                                <td hidden>id absensi</td>
                                <th scope="col">Tugas</th>
                                <th scope="col">Disetujui</th>
                                <th scope="col">Tambahan tugas</th>
                                <th scope="col">Status</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        {% for pegawai in presensi  %}
                        {% if person.nip == pegawai.nip.nip %}
                            {% for i in tugas_harian %}
                                
                                {% if i.id_absensi.id == pegawai.id %}
                                <tr>
                                    <td class="row_id" hidden><input type="text" name="id" id='id_tugas' value="{{i.id}}"></td>
                                    <td hidden><input type="text" name="id_absensi" id='absensi_id' value="{{i.id_absensi.id}}"></td>
                                    <td><input type="hidden" name="tgs_harian" id='tgs_harian_id' value="" disabled>{{i.nm_tugas_harian}}</td>
                                    <td><input type="checkbox" name="is_approve" id='is_approve_id' value="" {% if i.is_approved == True %}checked{% endif %}></td>
                                    <td><input type="text" name="tambah_tugas" id="tambah_tugas_id" value="{% if i.ket_tugas == None %}   {% else %} {{i.ket_tugas}} {% endif %}"></td>
                                    <td><input type="text" name="status_tugas" id="status_tugas_id"  value="{% if i.status == None %}   {% else %} {{i.status}} {% endif %}" disabled></td>
                                    <td><a class="btn btn-warning js-post-data" href="{% url 'update_task' i.id %}">approve</a></td>
                                </tr>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                        {% endfor %}
                </table>
               
              
        </div>
            
        {% endfor %}   
        
    </form>
    <p>is_caches: {{is_caches}}</p>
{% endblock %}

{% block javascript %}
    <script src="{%static 'js/main.js'%}"></script>
{% endblock  %}

task/templates/core/hukuman.html
{%extends 'core\base.html'%}

{% load static %}

{% block content %}

    <h1>Hukuman Pegawai</h1>
    
   <p>
    <button type="button" class="btn btn-primary js-create-hukuman">
        <span class="material-icons"></span> Buat hukuman
    </button>
   </p>
    {% comment %} <form action="/" method='POST'>
        {% csrf_token %} {% endcomment %}
        <h3>Pimpinan :  <input type="hidden" name="nm_pimpinan" value={{pimpinan.nama}}>{{pimpinan.nama}}</h3>
        <p></p>
        {% comment %} <div class="input-group mb-3">
                <label for="tgl_absensiid" class="col-sm-2">Tanggal</label>
                <input type="date" class="form-control col-sm-2" name="tgl_absensi" id="tgl_absensiid"> 
                <button class="btn btn-info" name="btn_cek_tgl"> cek tanggal</button>
        </div> {% endcomment %}
                
        <table class="table" id="hukuman-table">
                <thead class="table-primary">
                    <tr>
                        <th scope="col" class="text-center">No</th>
                        <th scope="col" class="text-center">Nip</th>
                        <th scope="col" class="text-center">Nama</th>
                        <th scope="col" class="text-center">jenis_hukuman</th>
                        <th scope="col" class="text-center">teguran</th>
                    </tr>
                </thead>
               <tbody>
                    {% include 'core\partial_daftar_hukuman.html' %}
               </tbody>
        </table>

    <div class="modal fade" id="modal-hukuman">
        <div class="modal-dialog">
            <div class="modal-content"></div>
        </div>
    </div>            
        
    {% comment %} </form> {% endcomment %}
{% endblock %}

{% block javascript %}
    <script src="{%static 'js/hukuman.js'%}"></script>
{% endblock  %}

task/templates/core/partial_buat_hukuman.html
{% load widget_tweaks %}

<form method="post" action="{% url 'buat-hukuman' %}" class="js-buat-hukuman-form">
    {% csrf_token %}
    <div class="modal-header">
        <button class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Buat Hukuman</h4>
    </div>
    <div class="modal-body">
        {% for field in form %}
            <div class="form-group {% if field.errors %}has-error{% endif %}">
                <label for="{{field.id_for_label}}">{{field.label}}</label>
                {% render_field field class="form-control" %}
                {% for error in field.errors %}
                    <p class="help-block">{{error }}</p>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"> Close </button>
        <button type="submit" class="btn btn-primary">Buat Hukuman</button>
    </div>
</form>

task/templates/core/partial_daftar_hukuman.html
{% for pelanggaran in hukuman %}
    <tr>
        <td>{{forloop.counter}}</td>
        <td>{{pelanggaran.nip.nip}}</td>
        <td>{{pelanggaran.nip.nama}}</td>
        <td>{{pelanggaran.get_jns_hukuman_display}}</td>
        <td>{{pelanggaran.teguran}}</td>
    </tr>
{% empty%}
    <tr>
        <td colspan="5" class="text-center bg-warning">Belum ada hukuman</td>
    </tr>
{% endfor %}

task/templates/core/savepeg.html
{% extends 'core\base.html' %}

{% block content %}

<p>{{msg}}</p>
<form action="{% url 'save_peg' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="submit">
</form>
{% endblock content %}

task/templates/core/tugas.html
{% extends 'core\base.html' %}

{% block content %}
    cek
    <form action="" method="post">
        {% csrf_token %}
        {{absensiform.as_p}}
        {{tugasform.as_p}}

        <input type="submit" value="submit">
    </form>
{% endblock content %}

task/templates/core/update_task.html
{% extends 'core\base.html' %}

{% block content %}
    <h3>Update Task</h3>
    <form action="">
        {% csrf_token %}
        {{tugasform}}
    </form>
    {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
    var formData = new FormData();
    {% comment %} 
    "#" menandakan memanggil id pada html 
    'title' variable tempat menyimpan nilai
    #title.val() mengambil nilai dari id title pada form html
    'action', 'create-post' cara kerjanya sama seperti form action, 
    processData dan contentType harus dimasukkan dalam fungsi .ajax

    {% endcomment %}
    {% comment %} $(document).on('click', '#submit', function(e){
        formData.append('title', $('#title').val())
        formData.append('description', $('#description').val())
        formData.append('image', $('#image')[0].files[0])
        formData.append('action', 'create-post')
        formData.append('csrfmiddlewaretoke', '{{} csrf_token }}')
        $.ajax({
            type: 'POST',
            url: '{% url "create-post" %}',
            data: formData,
            cache: false,
            processData: false,
            contentType: false,
            enctype: 'multipart/form-data',
            success: function(){
                alert('the post has been created')
            },
            error: function(xhr, errmsg, err){
                console.log(xhr.status + ":" + xhr.responseText)
            }
        })
    })
</script> {% endcomment %} 
{% endblock content %}